const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const output=process.env.APC_QA_OUTPUT||'/workspace/scratch/946773f06231/qa';fs.mkdirSync(output,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.APC_QA_CHROMIUM?{executablePath:process.env.APC_QA_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--disable-gpu']}: {})});const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await context.route('https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit',route=>route.fulfill({contentType:'text/javascript',body:`window.turnstile={render:(target,opts)=>{window.qaOptions=opts;document.querySelector(target).textContent='Security check (local test)';setTimeout(()=>opts.callback('local-qa-'+crypto.randomUUID()),10);return 1;},reset:()=>setTimeout(()=>window.qaOptions.callback('local-qa-'+crypto.randomUUID()),10)};`}));
await page.goto('http://localhost:8899/programmes');await page.waitForFunction(()=>!document.querySelector('#interest-submit').disabled);await page.evaluate(()=>document.fonts.ready);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(output,'programmes-mobile.png'),fullPage:true});
await page.locator('[name=name]').fill('QA Parent');await page.locator('[name=email]').fill('mobile@example.test');for(const v of ['volunteering','money','camp'])await page.locator(`[name=programmes][value=${v}]`).check();await page.locator('[name=firstChoice]').selectOption('volunteering');await page.locator('[name=ages][value="6-8"]').check();await page.locator('[name=location]').fill('Petaling Jaya');await page.locator('[name=saturday]').selectOption('either');await page.locator('[name=adultAvailability]').selectOption('yes');await page.locator('[name=adult]').check();await page.locator('[name=consent]').check();
// A failed save must leave all answers available and show no confirmation.
let fail=true;await page.route('**/api/programme-interest',async route=>{if(route.request().method()==='POST'&&fail){fail=false;return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'We could not confirm your request was saved. Please try again.'})});}return route.continue();});
await page.locator('#interest-submit').click();await page.waitForFunction(()=>document.querySelector('#form-status').textContent.includes('could not confirm')||!document.querySelector('#interest-submit').disabled);assert.equal(await page.locator('[name=email]').inputValue(),'mobile@example.test');assert.equal(await page.locator('#interest-confirmation').isVisible(),false);await page.waitForFunction(()=>!document.querySelector('#interest-submit').disabled);await page.locator('#interest-submit').click();await page.locator('#interest-confirmation').waitFor({state:'visible'});assert.match(await page.locator('#interest-confirmation').textContent(),/no automatic email/);await page.screenshot({path:path.join(output,'programmes-confirmation-mobile.png'),fullPage:true});
const admin=await browser.newContext({viewport:{width:1280,height:900},extraHTTPHeaders:{Authorization:'Basic '+Buffer.from('apc:local-review-only').toString('base64')}});const adminPage=await admin.newPage();await adminPage.goto('http://localhost:8899/content-os/programmes/');await adminPage.locator('#records article').waitFor();assert.match(await adminPage.locator('#summary').textContent(),/1 stored contact records · 0 verified households/);adminPage.on('dialog',dialog=>dialog.accept());await adminPage.locator('article select').selectOption('verified');await adminPage.getByRole('button',{name:'Save review'}).click();await adminPage.waitForFunction(()=>document.querySelector('#summary').textContent.includes('1 verified households'));assert.match(await adminPage.locator('#summary').textContent(),/Community Crew: 1 verified interested · 1 first choice/);assert.match(await adminPage.locator('#summary').textContent(),/Everyday Money: 1 verified interested · 0 first choice/);await adminPage.screenshot({path:path.join(output,'programmes-tracker.png'),fullPage:true});await adminPage.getByRole('button',{name:'Delete record'}).click();await adminPage.waitForFunction(()=>document.querySelector('#summary').textContent.includes('0 stored contact records'));
await page.goto('http://localhost:8899/programmes');await page.waitForFunction(()=>!document.querySelector('#interest-submit').disabled);await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:path.join(output,'programmes-desktop.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const np=await nojs.newPage();await np.goto('http://localhost:8899/programmes');assert.equal(await np.locator('noscript').isVisible(),true);assert.equal(await np.locator('#interest-submit').isDisabled(),true);assert.equal(errors.length,0,errors.join('\n'));
await browser.close();fs.writeFileSync(path.join(output,'browser-results.json'),JSON.stringify({passed:true,checks:['390px and 1440px no overflow','all three interests in one submission','failed save preserves answers','confirmed database save shows on-screen receipt','private tracker receives real local database record','verified-household counts and overlapping programme totals','verified first preference','deletion removes record','no JavaScript contact fallback','no browser exceptions'],boundary:'Local SQLite storage and simulated Turnstile. No production submission or real Turnstile test.'},null,2));console.log('Browser checks passed');})().catch(e=>{console.error(e);process.exit(1);});
