const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const output=process.env.APC_QA_OUTPUT||'/workspace/scratch/946773f06231/qa';fs.mkdirSync(output,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.APC_QA_CHROMIUM?{executablePath:process.env.APC_QA_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--disable-gpu']}: {})});const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await context.route('https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit',route=>route.fulfill({contentType:'text/javascript',body:`window.turnstile={render:(target,opts)=>{window.qaOptions=opts;document.querySelector(target).textContent='Security check (local test)';setTimeout(()=>opts.callback('local-qa-'+crypto.randomUUID()),10);return 1;},reset:()=>setTimeout(()=>window.qaOptions.callback('local-qa-'+crypto.randomUUID()),10)};`}));
await page.goto('http://localhost:8899/programmes');await page.waitForFunction(()=>!document.querySelector('#interest-submit').disabled);await page.evaluate(()=>document.fonts.ready);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.match(await page.locator('#availability-status').textContent(),/list is open/);assert.equal(await page.locator('[name=email]').isEnabled(),true);await page.screenshot({path:path.join(output,'programmes-mobile.png'),fullPage:true});


// A stalled security widget times out without losing answers, then recovers on retry.
const stalled=await context.newPage();await stalled.clock.install();
await stalled.route('https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit',route=>route.fulfill({contentType:'text/javascript',body:'window.turnstile={render:()=>1,remove:()=>{}};'}));
await stalled.goto('http://localhost:8899/programmes');await stalled.locator('[name=name]').fill('Preserved on retry');
await stalled.waitForFunction(()=>document.querySelector('#form-status').textContent.includes('Loading the security'));
await stalled.clock.fastForward(21000);await stalled.locator('#interest-retry').waitFor({state:'visible'});
assert.equal(await stalled.locator('#interest-submit').isDisabled(),true);assert.equal(await stalled.locator('[name=name]').inputValue(),'Preserved on retry');
await stalled.evaluate(()=>window.turnstile.render=(target,options)=>{options.callback('local-qa-retry');return 2;});
await stalled.locator('#interest-retry').click();await stalled.waitForFunction(()=>!document.querySelector('#interest-submit').disabled);
assert.equal(await stalled.locator('[name=name]').inputValue(),'Preserved on retry');await stalled.close();
// Shared text-input rules must not stretch native checkboxes or inflate row spacing.
for (const width of [320,390,1440]) {
 await page.setViewportSize({width,height:900});
 const rows=await page.locator('input[name=programmes]').evaluateAll(inputs=>inputs.map(input=>{const box=input.getBoundingClientRect(),row=input.closest('label').getBoundingClientRect();return {boxHeight:box.height,boxWidth:box.width,rowHeight:row.height,top:box.top-row.top};}));
 for(const row of rows){assert.equal(row.boxHeight,21);assert.equal(row.boxWidth,21);assert.ok(row.rowHeight>=44&&row.rowHeight<=68);assert.ok(row.top>=10&&row.top<=12);}
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
}
await page.setViewportSize({width:390,height:844});
// Explore without changing interest until the parent explicitly adds a choice.
await page.locator('#tab-money').click();assert.equal(await page.locator('#panel-money').isVisible(),true);assert.equal(await page.locator('[name=programmes][value=money]').isChecked(),false);
await page.locator('#add-programme').click();assert.equal(await page.locator('[name=programmes][value=money]').isChecked(),true);assert.equal(await page.locator('[name=firstChoice]').inputValue(),'money');
await page.locator('#tab-camp').click();await page.locator('#add-programme').click();assert.equal(await page.locator('[name=firstChoice]').inputValue(),'money');assert.match(await page.locator('#form-selection-summary').textContent(),/Everyday Money Skills, Fitness & Adventure Camp/);
await page.locator('[name=programmes][value=camp]').uncheck();assert.equal(await page.locator('#add-programme').getAttribute('aria-pressed'),'false');
await page.locator('#tab-camp').focus();await page.keyboard.press('Home');assert.equal(await page.locator('#tab-volunteering').getAttribute('aria-selected'),'true');
await page.locator('#step-2').click();assert.equal(await page.locator('#coaching-2').isVisible(),true);await page.locator('#step-2').focus();await page.keyboard.press('End');assert.equal(await page.locator('#coaching-3').isVisible(),true);await page.keyboard.press('Home');
await page.locator('[name=programmes][value=money]').uncheck();
await page.locator('[name=name]').fill('QA Parent');await page.locator('[name=email]').fill('mobile@example.test');for(const v of ['volunteering','money','camp'])await page.locator(`[name=programmes][value=${v}]`).check();await page.locator('[name=firstChoice]').selectOption('volunteering');await page.locator('[name=ages][value="6-8"]').check();await page.locator('[name=location]').fill('Petaling Jaya');await page.locator('[name=saturday]').selectOption('either');await page.locator('[name=adultAvailability]').selectOption('yes');await page.locator('[name=adult]').check();await page.locator('[name=consent]').check();
// A failed save must leave all answers available and show no confirmation.
let fail=true;await page.route('**/api/programme-interest',async route=>{if(route.request().method()==='POST'&&fail){fail=false;return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'We could not confirm your request was saved. Please try again.'})});}return route.continue();});
await page.locator('#interest-submit').click();await page.waitForFunction(()=>document.querySelector('#form-status').textContent.includes('could not confirm')||!document.querySelector('#interest-submit').disabled);assert.equal(await page.locator('[name=email]').inputValue(),'mobile@example.test');assert.equal(await page.locator('#interest-confirmation').isVisible(),false);await page.waitForFunction(()=>!document.querySelector('#interest-submit').disabled);assert.match(await page.locator('#form-status').textContent(),/could not confirm/);await page.locator('#interest-submit').click();await page.locator('#interest-confirmation').waitFor({state:'visible'});assert.match(await page.locator('#interest-confirmation').textContent(),/no automatic email/);assert.equal(await page.locator('.explorer-actions').isVisible(),false);await page.screenshot({path:path.join(output,'programmes-confirmation-mobile.png'),fullPage:true});
const admin=await browser.newContext({viewport:{width:1280,height:900}});const adminPage=await admin.newPage();await adminPage.goto('http://localhost:8899/content-os/programmes/');await adminPage.locator('#password').fill('local-review-only');await adminPage.getByRole('button',{name:'Sign in',exact:true}).click();await adminPage.locator('#records article').waitFor();assert.match(await adminPage.locator('#summary').textContent(),/1 stored contact records · 0 verified households/);adminPage.on('dialog',dialog=>dialog.accept());await adminPage.locator('article select').selectOption('verified');await adminPage.getByRole('button',{name:'Save review'}).click();await adminPage.waitForFunction(()=>document.querySelector('#summary').textContent.includes('1 verified households'));assert.match(await adminPage.locator('#summary').textContent(),/Community Volunteering: 1 verified interested · 1 first choice/);assert.match(await adminPage.locator('#summary').textContent(),/Everyday Money Skills: 1 verified interested · 0 first choice/);await adminPage.locator('article input[type=date]').fill('2020-01-01');await adminPage.getByRole('button',{name:'Save review'}).click();await adminPage.waitForFunction(()=>document.querySelector('#summary').textContent.includes('1 follow-ups due'));await adminPage.locator('#filter').selectOption('due');assert.equal(await adminPage.locator('#records article').count(),1);await adminPage.screenshot({path:path.join(output,'programmes-tracker.png'),fullPage:true});await adminPage.locator('#filter').selectOption('no-date');assert.equal(await adminPage.locator('#records article').count(),0);await adminPage.locator('#filter').selectOption('all');await adminPage.goto('http://localhost:8899/content-os/programmes/follow-up');await adminPage.waitForFunction(()=>document.querySelector('#follow-up-status').textContent.includes('Counts loaded'));assert.match(await adminPage.locator('#follow-up-totals').textContent(),/Follow-ups due: 1/);await adminPage.screenshot({path:path.join(output,'follow-up-overview.png'),fullPage:true});await adminPage.goto('http://localhost:8899/content-os/programmes/');await adminPage.locator('#records article').waitFor();await adminPage.getByRole('button',{name:'Delete record'}).click();await adminPage.waitForFunction(()=>document.querySelector('#summary').textContent.includes('0 stored contact records'));
await page.goto('http://localhost:8899/programmes');await page.waitForFunction(()=>!document.querySelector('#interest-submit').disabled);await page.setViewportSize({width:320,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:path.join(output,'programmes-desktop.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const np=await nojs.newPage();await np.goto('http://localhost:8899/programmes');assert.equal(await np.locator('noscript').isVisible(),true);assert.equal(await np.locator('[data-panel]:visible').count(),3);assert.equal(await np.locator('[data-coaching]:visible').count(),4);assert.equal(await np.locator('#interest-submit').isDisabled(),true);assert.equal(errors.length,0,errors.join('\n'));
// Unavailable forms must explain their state before the family enters details.
const closed=await browser.newContext({viewport:{width:390,height:844}});const cp=await closed.newPage();await cp.route('**/api/programme-interest',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({enabled:false})}));await cp.goto('http://localhost:8899/programmes');await cp.waitForFunction(()=>document.querySelector('#availability-status').textContent.includes('not open'));assert.equal(await cp.locator('[name=email]').isDisabled(),true);assert.equal(await cp.locator('#interest-submit').isDisabled(),true);await cp.screenshot({path:path.join(output,'programmes-closed-mobile.png'),fullPage:true});await cp.setViewportSize({width:1440,height:1000});await cp.screenshot({path:path.join(output,'programmes-closed-desktop.png'),fullPage:true});
await page.goto('http://localhost:8899/resources');await page.getByText('Taking part in community',{exact:true}).click();assert.equal(await page.getByRole('link',{name:'Explore upcoming programmes',exact:true}).getAttribute('href'),'/programmes');await page.locator('#browse-all').screenshot({path:path.join(output,'resources-community.png')});
await adminPage.goto('http://localhost:8899/content-os/programmes/readiness');assert.match(await adminPage.locator('#readiness-result').textContent(),/8 of 8/);await adminPage.screenshot({path:path.join(output,'readiness-review.png'),fullPage:true});for(const select of await adminPage.locator('.readiness-grid select').all())await select.selectOption('confirmed');assert.match(await adminPage.locator('#readiness-result').textContent(),/do not approve a launch/);await adminPage.locator('[name=host]').selectOption('action');assert.match(await adminPage.locator('#readiness-result').textContent(),/1 of 8/);await adminPage.screenshot({path:path.join(output,'readiness-desktop.png'),fullPage:true});await adminPage.reload();assert.match(await adminPage.locator('#readiness-result').textContent(),/8 of 8/);await adminPage.setViewportSize({width:390,height:844});assert.equal(await adminPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await adminPage.screenshot({path:path.join(output,'readiness-mobile.png'),fullPage:true});
const unauthorised=await context.request.get('http://localhost:8899/content-os/programmes/readiness',{maxRedirects:0});assert.ok([302,401,403].includes(unauthorised.status()));
// Resource links must deliver the reviewed document bytes behind authentication.
await adminPage.setViewportSize({width:1280,height:900});await adminPage.goto('http://localhost:8899/content-os/programmes/resources');await adminPage.evaluate(()=>document.fonts.ready);assert.equal(await adminPage.locator('h1').textContent(),'Prepare the first Saturday visit.');assert.equal(await adminPage.locator('[aria-current=page]').textContent(),'Resources');
for(const link of await adminPage.locator('a[download]').all()){
 const href=await link.getAttribute('href');const file=href.split('/').pop();const downloadEvent=adminPage.waitForEvent('download');await link.click();const download=await downloadEvent;assert.equal(download.suggestedFilename(),file);assert.deepEqual(fs.readFileSync(await download.path()),fs.readFileSync(path.join(__dirname,'../../content-os/programmes/files',file)));
 const denied=await context.request.get('http://localhost:8899'+href,{maxRedirects:0});assert.equal(denied.status(),302);assert.equal(new URL(denied.headers().location).searchParams.get('next'),href);
}
await adminPage.screenshot({path:path.join(output,'programme-resources-desktop.png'),fullPage:true});await adminPage.setViewportSize({width:390,height:844});assert.equal(await adminPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await adminPage.screenshot({path:path.join(output,'programme-resources-mobile.png'),fullPage:true});
await adminPage.getByRole('link',{name:'Interest tracker',exact:true}).click();assert.equal(await adminPage.locator('[aria-current=page]').textContent(),'Interest tracker');assert.equal(await adminPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await adminPage.getByRole('link',{name:'Readiness checklist',exact:true}).click();assert.equal(await adminPage.locator('[aria-current=page]').textContent(),'Readiness checklist');await adminPage.getByRole('link',{name:'Resources',exact:true}).click();await adminPage.locator('summary').click();assert.match(await adminPage.locator('.planning-details').textContent(),/not included/);
await browser.close();fs.writeFileSync(path.join(output,'browser-results.json'),JSON.stringify({passed:true,checks:['390px and 1440px no overflow','programme tabs and keyboard navigation','explicit selection syncs to form in both directions','existing first choice preserved','all four coaching steps and no-JS fallback','closed capture prevents data entry','follow-up due and no-date filters','protected readiness checklist and reset','resources programme discovery','all four protected PDF and Word downloads match source bytes','resource hub navigation and mobile layouts','all three interests in one submission','failed save preserves answers','confirmed database save shows on-screen receipt','private tracker receives real local database record','verified-household counts and overlapping programme totals','verified first preference','deletion removes record','no JavaScript contact fallback','no browser exceptions'],boundary:'Local SQLite storage and simulated Turnstile. No production submission or real Turnstile test.'},null,2));console.log('Browser checks passed');})().catch(e=>{console.error(e);process.exit(1);});
