// Local QA only. This file is outside the public build allowlist.
import http from 'node:http';import {readFile} from 'node:fs/promises';import {fileURLToPath} from 'node:url';import {resolve,extname} from 'node:path';
import {database} from './db.mjs';import {onRequest as publicApi} from '../../functions/api/programme-interest.js';import {onRequest as adminApi} from '../../functions/api/content-os/programmes/index.js';import {onRequest as middleware} from '../../functions/_middleware.js';import {PUBLIC_FILES} from '../../scripts/build-site.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url));const db=database();const tokens=new Set();
const env={APC_CONTENT_OS_DB:db,APC_PROGRAMME_INTEREST_ENABLED:process.env.APC_QA_CAPTURE_STATE==='closed'?'false':'true',APC_PROGRAMME_TURNSTILE_SITEKEY:'local-qa-only',APC_PROGRAMME_TURNSTILE_SECRET:'local-qa-only',APC_CONTENT_OS_ENVIRONMENT:'production',APC_CONTENT_OS_AUTH:'local-review-only'};
globalThis.fetch=async(url,options)=>{if(!String(url).startsWith('https://challenges.cloudflare.com/turnstile/'))throw new Error('Unexpected network');const {response}=JSON.parse(options.body);const success=response.startsWith('local-qa-')&&!tokens.has(response);tokens.add(response);return Response.json({success,hostname:'localhost',action:'programme-interest'});};
const mime={'.html':'text/html','.css':'text/css','.js':'text/javascript','.webp':'image/webp','.png':'image/png','.woff2':'font/woff2','.pdf':'application/pdf','.docx':'application/vnd.openxmlformats-officedocument.wordprocessingml.document'};
http.createServer(async(incoming,outgoing)=>{try{const chunks=[];for await(const chunk of incoming)chunks.push(chunk);const url=new URL(incoming.url,'http://localhost:8899');const request=new Request(url,{method:incoming.method,headers:incoming.headers,...(!['GET','HEAD'].includes(incoming.method)?{body:Buffer.concat(chunks)}:{})});
const serve=async()=>{if(url.pathname==='/api/programme-interest')return publicApi({request,env});if(url.pathname==='/api/content-os/programmes')return adminApi({request,env});let path=decodeURIComponent(url.pathname).replace(/^\//,'');if(!path)path='index.html';if(path.endsWith('/'))path+='index.html';else if(!extname(path))path+='.html';if(!PUBLIC_FILES.includes(path))return new Response('Not found',{status:404});try{return new Response(await readFile(resolve(root,path)),{headers:{'Content-Type':mime[extname(path)]||'application/octet-stream'}});}catch{return new Response('Not found',{status:404});}};
const result=await middleware({request,env,next:serve});outgoing.writeHead(result.status,Object.fromEntries(result.headers));outgoing.end(Buffer.from(await result.arrayBuffer()));}catch(error){outgoing.writeHead(500);outgoing.end('QA server error');}}).listen(8899,'0.0.0.0',()=>console.log('Local QA preview on http://localhost:8899/programmes'));
