import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {onRequest as publicApi} from '../functions/api/programme-interest.js';import {onRequest as adminApi} from '../functions/api/content-os/programmes/index.js';import {onRequest as middleware} from '../functions/_middleware.js';import {database} from './programmes/db.mjs';
const valid=()=>({name:'Example Parent',email:'parent@example.test',phone:'',programmes:['volunteering','money','camp'],firstChoice:'volunteering',ages:['6-8'],location:'Petaling Jaya',saturday:'either',adultAvailability:'yes',supportDiscussion:'not-now',updates:false,adult:true,consent:true,consentVersion:'programmes-2026-09-v1',token:'test-token'});
const env=()=>({APC_CONTENT_OS_DB:database(),APC_PROGRAMME_INTEREST_ENABLED:'true',APC_PROGRAMME_TURNSTILE_SITEKEY:'test',APC_PROGRAMME_TURNSTILE_SECRET:'test',APC_CONTENT_OS_ENVIRONMENT:'production',APC_CONTENT_OS_AUTH:'local-tests-only'});
function req(method='POST',body=valid(),path='/api/programme-interest',origin='https://example.test'){return new Request('https://example.test'+path,{method,headers:{Origin:origin,'Content-Type':'application/json'},...(method==='GET'?{}:{body:JSON.stringify(body)})});}
const originalFetch=globalThis.fetch;globalThis.fetch=async()=>Response.json({success:true,hostname:'example.test',action:'programme-interest'});
process.on('exit',()=>{globalThis.fetch=originalFetch;});
test('stores all interests in one contact record, with opt-out intact',async()=>{const e=env();const r=await publicApi({request:req(),env:e});assert.equal(r.status,200);const rows=e.APC_CONTENT_OS_DB.sql.prepare('select * from programme_interest').all();assert.equal(rows.length,1);assert.equal(JSON.parse(rows[0].programmes).length,3);assert.equal(rows[0].updates,0);assert.equal(rows[0].status,'new');});
test('duplicate email is case-insensitive and never overwrites answers or consent',async()=>{const e=env();await publicApi({request:req(),env:e});const changed={...valid(),email:'PARENT@EXAMPLE.TEST',updates:true,name:'Different person'};const r=await publicApi({request:req('POST',changed),env:e});assert.deepEqual(await r.json(),{received:true});const rows=e.APC_CONTENT_OS_DB.sql.prepare('select * from programme_interest').all();assert.equal(rows.length,1);assert.equal(rows[0].updates,0);assert.equal(rows[0].name,'Example Parent');});
test('rejects invalid choices, empty fields, missing consent and oversize content',async()=>{for(const patch of [{programmes:[]},{ages:[]},{consent:false},{adult:false},{updates:'yes'},{email:'bad'},{firstChoice:'other'},{saturday:'never'},{name:'x'.repeat(81)},{phone:'letter-number'},{consentVersion:'wrong'}]){assert.equal((await publicApi({request:req('POST',{...valid(),...patch}),env:env()})).status,400);}assert.equal((await publicApi({request:req('POST',{...valid(),name:'x'.repeat(9000)}),env:env()})).status,400);});
test('fails closed before activation and on cross-origin requests',async()=>{const e=env();e.APC_PROGRAMME_INTEREST_ENABLED='false';assert.equal((await publicApi({request:req(),env:e})).status,503);assert.equal((await publicApi({request:req('POST',valid(),'/api/programme-interest','https://other.test'),env:env()})).status,403);const config=await publicApi({request:req('GET'),env:e});assert.deepEqual(await config.json(),{enabled:false,sitekey:null,consentVersion:'programmes-2026-09-v1'});});
test('requires valid Turnstile result, hostname and action',async()=>{for(const result of [{success:false},{success:true,hostname:'evil.test',action:'programme-interest'},{success:true,hostname:'example.test',action:'other'}]){globalThis.fetch=async()=>Response.json(result);const e=env();assert.equal((await publicApi({request:req(),env:e})).status,400);assert.equal(e.APC_CONTENT_OS_DB.sql.prepare('select count(*) n from programme_interest').get().n,0);}globalThis.fetch=async()=>Response.json({success:true,hostname:'example.test',action:'programme-interest'});});
test('database failure never claims success',async()=>{const e=env();e.APC_CONTENT_OS_DB={prepare(){throw new Error('unavailable');}};const r=await publicApi({request:req(),env:e});assert.equal(r.status,503);assert.match((await r.json()).error,/could not confirm/);});
test('middleware blocks anonymous API, redirects protected page, and authorises a valid local credential',async()=>{let reached=false;const e=env();const next=async()=>{reached=true;return Response.json({ok:true});};const denied=await middleware({request:req('GET',null,'/api/content-os/programmes'),env:e,next});assert.equal(denied.status,401);assert.equal(reached,false);const page=await middleware({request:req('GET',null,'/content-os/programmes/'),env:e,next});assert.equal(page.status,302);const request=req('GET',null,'/api/content-os/programmes');request.headers.set('Authorization','Basic '+btoa('apc:local-tests-only'));const ok=await middleware({request,env:e,next});assert.equal(ok.status,200);assert.equal(ok.headers.get('Cache-Control'),'private, no-store');assert.equal(reached,true);});
test('admin can verify, follow up and delete, but cross-origin writes are refused',async()=>{const e=env();await publicApi({request:req(),env:e});let r=await adminApi({request:req('GET',null,'/api/content-os/programmes'),env:e});const id=(await r.json()).records[0].id;assert.equal((await adminApi({request:req('PATCH',{id,status:'verified',nextFollowup:'2026-10-03'},'/api/content-os/programmes'),env:e})).status,200);r=await adminApi({request:req('GET',null,'/api/content-os/programmes'),env:e});assert.equal((await r.json()).records[0].status,'verified');assert.equal((await adminApi({request:req('PATCH',{id,status:'verified',nextFollowup:'2026-02-30'},'/api/content-os/programmes'),env:e})).status,400);assert.equal((await adminApi({request:req('DELETE',{id},'/api/content-os/programmes','https://evil.test'),env:e})).status,403);await adminApi({request:req('DELETE',{id},'/api/content-os/programmes'),env:e});assert.equal(e.APC_CONTENT_OS_DB.sql.prepare('select count(*) n from programme_interest').get().n,0);});
test('expired entries are removed on review',async()=>{const e=env();await publicApi({request:req(),env:e});e.APC_CONTENT_OS_DB.sql.prepare('update programme_interest set created_at=?').run('2000-01-01T00:00:00.000Z');const r=await adminApi({request:req('GET',null,'/api/content-os/programmes'),env:e});assert.equal((await r.json()).records.length,0);});
test('routing and build include the new public and protected paths',()=>{const routes=JSON.parse(readFileSync(new URL('../_routes.json',import.meta.url)));assert.ok(routes.include.includes('/api/programme-interest'));assert.ok(routes.include.includes('/api/content-os/*'));assert.ok(routes.include.includes('/content-os/*'));const build=readFileSync(new URL('../scripts/build-site.mjs',import.meta.url),'utf8');assert.ok(build.includes('"programmes.html"'));assert.ok(build.includes('"content-os/programmes/app.js"'));assert.ok(!build.includes('"migrations/0012_programme_interest.sql"'));});
