/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=pathway-preview/wrangler.jsonc --include-runtime=false pathway-preview/worker-configuration.d.ts` (hash: 9d08e9ac5d70721af424a17c371672d5)
interface __BaseEnv_Env {
	PATHWAY_DB: D1Database;
	APC_PATHWAY_ENVIRONMENT: "preview";
	APC_PATHWAY_PRODUCTION_ENABLED: "false";
	APC_PATHWAY_REAL_CLIENT_DATA_ENABLED: "false";
	APC_PATHWAY_D1_MODE: "synthetic-preview";
	APC_PATHWAY_R2_MODE: "disabled";
	APC_PATHWAY_ALLOWED_CLIENT_ID: "DEMO-CLIENT-001";
	APC_PATHWAY_NOTICE_VERSION: "synthetic-notice-v1";
	APC_PATHWAY_TERMS_VERSION: "synthetic-terms-v1";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APC_PATHWAY_ENVIRONMENT" | "APC_PATHWAY_PRODUCTION_ENABLED" | "APC_PATHWAY_REAL_CLIENT_DATA_ENABLED" | "APC_PATHWAY_D1_MODE" | "APC_PATHWAY_R2_MODE" | "APC_PATHWAY_ALLOWED_CLIENT_ID" | "APC_PATHWAY_NOTICE_VERSION" | "APC_PATHWAY_TERMS_VERSION">> {}
}
